txt = "Hello World"
print("1. Jumlah karakter:")
print(len(txt))
print()
print("2. Karakter terakhir:")
print(txt[-1])
print()
print("3. Karakter index ke-2 sampai ke-4:")
print(txt[2:5])
print()
print("4. Hilangkan spasi:")
print(txt.replace(" ", ""))
print()
print("5. Huruf besar:")
print(txt.upper())
print()
print("6. Huruf kecil:")
print(txt.lower())
print()
print("7. Ganti H dengan J:")
print(txt.replace("H", "J"))
